### ISSUE TITLE
OpenFX

### ISSUE THREAD

**Issue by RoyiAvital** [ofxa/openfx#10]
Hello,
I don't understand something about OpenFX.

What's the difference between:

http://en.wikipedia.org/wiki/OpenFX / http://www.openfx.org/

And:

http://openfx.sourceforge.net/ / http://natron.inria.fr/561/

While the first says it only supports Win32, it seems others say they support all OS's.

Thank You.

**Comment by MrKepzie** [comment]
@RoyiAvital The document was misleading, I did not meant that the OpenFX standard was not supported anymore, but that the C++ layer offered by the original repository (this one) is quite outdated and contains bugs and missing implementations.  We tried to fix these issues in https://github.com/devernay/openfx , as well as update the repository to OpenFX 1.3. 
I updated the document you pointed to clarify the matter.

**Comment by RoyiAvital** [comment]
What I wonder the most, If I write plug in's using your API's will it work on other programs which are supporting OpenFX?

**Comment by MrKepzie** [comment]
Yes, of course. Note that some hosts do not implement correctly all features of OpenFX 1.3, and sometimes it is a bit tedious to make things portable across all hosts.
You should try Natron while developing your plug-ins, this is a good way to debug since you’ve got complete access to the source code. 
You can then try other hosts (by attaching process to your plug-in) and compare the behaviour which should in theory be the same.

**Comment by garyo** [comment]
Closing, not really an issue with the spec or code.
